services:
  rbmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - prodplace
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mongodb-data:
    driver: local
  products-db-data:
    driver: local
  currencies-db-data:
    driver: local
  identity-db-data:
    driver: local
  redis-cache-data:
    driver: local
  rabbitmq-data:
    driver: local

networks:
  prodplace:
    driver: bridge