services:
  rbmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - prodplace
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 5s
      timeout: 10s
      retries: 10

  keycloak:
    image: prodplace-keycloak-prebuilt:latest
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_USERNAME: keycloak_db_user
      KC_DB_PASSWORD: keycloak_db_user_password
      KC_HOSTNAME: localhost
    networks:
      - prodplace
    restart: always
    depends_on:
      - keycloak-db


  keycloak-db:
    image: postgres:17-alpine
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_db_user
      POSTGRES_PASSWORD: keycloak_db_user_password
    networks:
      - prodplace

volumes:
  mongodb-data:
    driver: local
  products-db-data:
    driver: local
  currencies-db-data:
    driver: local
  identity-db-data:
    driver: local
  redis-cache-data:
    driver: local
  rabbitmq-data:
    driver: local
  orders-data:
    driver: local
  customers-data:
    driver: local
  keycloak-data:
    driver: local

networks:
  prodplace:
    driver: bridge