services:
  reverse-proxy:
    image: reverse-proxy
    build:
      context: .
      dockerfile: ./ProxyService/Dockerfile
    networks:
      - prodplace
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PROJECT_NAME=ProxyService
    ports:
      - "8099:8080"

  products-service:
    image: products-service
    build:
      context: .
      dockerfile: ./ProductsService/Dockerfile
    depends_on:
      products-db:
        condition: service_healthy
      rbmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      - prodplace
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PROJECT_NAME=ProductsService
    expose:
      - "8080"

  price-service:
    image: price-service
    build:
      context: .
      dockerfile: ./PriceService/Dockerfile
    networks:
      - prodplace
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PROJECT_NAME=PriceService

  currency-rates-service:
    image: currency-rates-service
    build:
      context: .
      dockerfile: ./CurrencyRatesService/Dockerfile
    depends_on:
      currencies-db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    networks:
      - prodplace
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PROJECT_NAME=CurrencyRatesService

  playground-service:
    image: playground-service
    build:
      context: .
      dockerfile: ./PlaygroundService/Dockerfile
    depends_on:
      redis-cache:
        condition: service_healthy
    networks:
      - prodplace
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PROJECT_NAME=PlaygroundService