volumes:
  mongodb-data:
    driver: local
  products-db-data:
    driver: local
  currencies-db-data:
    driver: local
  redis-cache-data:
    driver: local
  rabbitmq-data:
    driver: local

networks:
  products-service:
    driver: bridge