<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Protobuf" />
        <PackageReference Include="Grpc.Net.Client" />
        <PackageReference Include="Grpc.Net.ClientFactory" />
        <PackageReference Include="Grpc.Tools">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    </ItemGroup>

    <ItemGroup>
      <Protobuf Include="..\ProdPlace.Grpc\Protos\role_admin.proto" GrpcServices="Client" Link="Protos\role_admin.proto" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ProdPlace.ServiceDefaults\ProdPlace.ServiceDefaults.csproj" />
    </ItemGroup>

</Project>

