<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="Respawn" />
        <PackageReference Include="Testcontainers" />
        <PackageReference Include="Testcontainers.Keycloak" />
        <PackageReference Include="Testcontainers.MongoDb" />
        <PackageReference Include="Testcontainers.MsSql" />
        <PackageReference Include="Testcontainers.PostgreSql" />
        <PackageReference Include="Testcontainers.RabbitMq" />
        <PackageReference Include="xunit.abstractions" />
        <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CustomerService\CustomerService.csproj" />
        <ProjectReference Include="..\IdentityService\IdentityService.csproj" />
        <ProjectReference Include="..\Prodplace.Admin\Prodplace.Admin.csproj">
            <Aliases>AdminSUT</Aliases>
        </ProjectReference>
        <ProjectReference Include="..\ProductsService\ProductsService.csproj">
            <Aliases>ProductsServiceSUT</Aliases>
        </ProjectReference>
    </ItemGroup>

</Project>

