namespace IntegrationTests.Factories;

[CollectionDefinition(nameof(ContainersFactoryCollectionDefinition))]
public class ContainersFactoryCollectionDefinition : ICollectionFixture<ContainersFactory>;