FROM postgres:17-alpine

# Add any additional configurations or installations here if needed
# For example, you might want to install additional PostgreSQL extensions

# Copy custom initialization scripts
#COPY ./init.sql /docker-entrypoint-initdb.d/

# Set the default command to run when starting the container
CMD ["postgres"]