<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
      <PackageReference Include="Hangfire.Core" Version="1.8.*" />
      <PackageReference Include="Hangfire.SqlServer" Version="1.8.*" />
      <PackageReference Include="Hangfire.AspNetCore" Version="1.8.*" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.5" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.5">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.5" />
      <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="9.0.5" />
      <PackageReference Include="StackExchange.Redis" Version="2.8.37" />
    </ItemGroup>

</Project>
